var new_lang = {
lt1: 'Innovazione e rivoluzione nella cardiologia',
lt2: 'Solo ora!<br>Il vostro sconto personale:',
lt3: 'Prezzo in farmacia:',
lt4: 'In offerta rimangono solo:',
lt5: 'confezioni',
lt6: 'Sconfigge l’ipertensione',
lt7: 'e tutti i suoi sintomi',
lt8: 'L’ibera completamente dall’ipertensione',
lt9: 'in 14 giorni!',
lt10: 'Difende cuore e vasi sanguigni dagli sforzi eccessivi',
lt11: 'Regola la pressione in maniera completamente naturale',
lt12: 'Scegliete la nazione:',
lt13: 'Inserite il nome:',
lt14: 'Inserite il numero di telefono:',
lt15: 'Ordinare',
lt16: 'fino alla fine dell’offerta:',
lt17: 'ore',
lt18: 'minuti',
lt19: 'secondi',
lt20: 'Continuate tutt’ora a combattere l’ipertensione',
lt21: 'in maniera scorretta?',
lt22: 'L’abbassamento artificiale della pressione arteriosa con le pillole non fa che peggiorare il problema!',
lt23: 'I preparati per abbassare la pressione trasformano i vasi sanguigni delle persone in vasi sanguigni di anziani, e comportano gravi effetti collaterali!',
lt24: 'Per liberarsi in maniera efficace e sicura dell’ipertensione è necessario un preparato che ',
lt25: 'MANTERRA’ continuamente la pressione nella norma,',
lt26: 'aiutando allo stesso modo l’organismo a combattere la causa dell’aumento di pressione.',
lt27: 'contro le malattie del cuore e dei vasi sanguigni!',
lt28: '"Elimina la causa, e scomparirà anche la malattia!"',
lt29: 'Ippocrate',
lt30: 'E’ il primo preparato, che NATURALMENTE,  e non in maniera artificiale, abbassa la pressione arteriosa e  ',
lt31: 'libera completamente dai problemi di pressione arteriosa!',
lt32: 'L’eliminazione delle malattie di carattere ipertensivo con ReCardio avviene attraverso la stabilizzazione della pressione sanguigna e l’eliminazione delle cause principali delle malattie di questo tipo.',
lt33: 'Tecnologi unica',
lt34: 'Vasodilat',
lt35: 'L’Ipocapnia è una continua mancanza di ossigeno nel sangue',
lt36: 'è la prima causa dell’ipertensione arteriosa',
lt37: ' — continua situazione di contrazione innaturale (spasmi) delle valvole e delle piccole arterie.',
lt38: 'Abbassamento della concentrazione d’ossigeno',
lt39: 'nel sangue arterioso',
lt40: 'Si attiva un particolare meccanismo di difesa nell’organismo ',
lt41: 'il vaso sanguigno si contrae di colpo',
lt42: 'AVVIENE UNO SPASMO! LA PRESSIONE CRESCE IN MANIERA ESPONENZIALE!',
lt43: 'Con l’aiuto della tecnologia Vasodilat ReCardio',
lt44: 'aiuta a mantenere la concentrazione d’ossigeno necessaria',
lt45: 'nel sangue.',
lt46: 'Più ossigeno c’è nel sangue',
lt47: 'minore è la pressione sui vasi sanguigni.',
lt48: 'GLI SPASMI DIMINUISCONO!',
lt49: 'LA PRESSIONE TORNA NELLA NORMA',
lt50: 'ELIMINA LE CAUSE PRINCIPALI',
lt51: 'DELLA MANCANZA DI OSSIGENO',
lt52: 'La pressione alta è una reazione necessaria dell’organismo contro:',
lt53: 'Stress',
lt56: 'Ortica',
lt57: 'Contiene una grande quantità di vitamine, acidi, e componenti attivi. Super efficace nella cura delle malattie del cuore. Aiuta ad eliminare il nervosismo, migliora il lavoro del cuore, migliora la circolazione sanguigna, scioglie gli ammassi sanguigni e rinforza la capacità di lasciar passare il sangue dei vasi sanguigni..',
lt59: 'Spasmi dei vasi sanguigni',
lt62: 'Biancospino',
lt63: 'Тонизирует сердечную мышцу, оказывает сосудорасширяющее действие, предотвращает образование бляшек и улучшает показатели крови. Нормализует уровень холестерина в крови.',
lt64: 'Vitamina В6',
lt65: 'Abbassa la pressione sanguigna nei tessuti e negli apparati dell’organismo, aiuta ad eliminare i liquidi in eccesso.',
lt66: 'Riboflavina, vitamina B2',
lt67: 'Una delle vitamine più importanti per l’organismo umano. Necessaria per la formazione di globuli rossi e anticorpi, per far respirare le cellule e per farle crescere .',
lt68: 'Sindrome metabolica',
lt69: 'Tiamina, Vitamina B1',
lt70: 'Componente senza il quale il sistema nervoso non può funzionare stabilmente, ha effetti rilassanti. Migliora la circolazione sanguigna e  partecipa all’Emopoiesi.',
lt74: 'EFFICACIA DIMOSTRATA',
lt75: 'CLINICAMENTE:',
lt76: 'Stabilizza la pressione entro 15 minuti,<br>senza sbalzi e cali improvvisi regola la pressione.',
lt77: 'nel 99% dei casi',
lt78: 'Elimina l’elasticità delle pareti dei vasi, scioglie i grumi sanguigni impedendo la formazione di trombi',
lt79: 'nel 98% dei casi',
lt80: 'Abbassa il livello dell’ormone dello stress e favorisce la formazione di ossigeno',
lt81: 'nel 96% dei casi',
lt82: 'E’ efficace in caso di problemi di sonno e stabilizza il ciclo "sonno-veglia"',
lt83: 'nel 91% dei casi',
lt84: 'E’ stato effettuato un studio da parte dell’Istituto di Ricerca per le Malattie del sistema Cardiovascolare durante il 2015.<br>1 000 volontari con casi di ipertensione a diversi stadi',
lt85: ' hanno assunto ReCardio per due settimane.',
lt86: 'Alla fine delle ricerche sono stati ottenuti i seguenti risultati:',
lt87: 'nel 98% dei casi',
lt88: 'la pressione si è stabilizzata nella norma',
lt89: 'dopo la prima assunzione',
lt90: 'nel 97% dei casi',
lt91: 'sono scomparsi i sintomi dell’ipertensione',
lt92: 'dopo l’assunzione di un ciclo di due settimane',
lt93: 'nell’ 81% dei casi',
lt94: 'in maniera evidente',
lt95: 'è diminuito il numero di attacchi di ipertensione',
lt96: 'già dopo 3 giorni di assunzione',
lt97: '9 malati di ipertensione su 10 confermano:',
lt98: ' è più efficace della maggior parte dei preparati in precedenza prescritti dai dottori!',
lt99: 'Aiuto istantaneo',
lt100: 'Naturale e sicuro',
lt101: 'Non comporta effetti collaterali e dipendenza',
lt102: 'Raccomandato dai cardiologi',
lt103: 'Secondo i risultati dei test clinici posso con tranquillità affermare che',
lt104: 'XX  è al giorno d’oggi il preparato in assoluto più efficace nella lotta contro l’ipertensione.',
lt105: 'Nel 98% dei casi  viene eliminata la CAUSA stessa dell’ipertensione arteriosa, e non solo i sintomi.',
lt106: 'Già dopo 1-3 giorni di assunzione avviene un miglioramento dei valori della pressione sanguigna,',
lt107: 'scompaiono i mal di testa, l’aritmia, la tachicardia e altri problemi dovuti ad un cattivo funzionamento del sistema cardiovascolare. ',
lt108: 'In più, ',
lt109: 'ReCardio ha un potente effetto allarga vasi sanguigni',
lt110: 'e lavora il lavoro del sistema circolatorio, dei sistemi immunitario e nervoso, e ciò è fondamentale per mantenere una corretta pressione arteriosa.',
lt111: 'Raccomando il preparato in questione ai malati di ipertensione a qualsiasi stadio di sviluppo della malattia',
lt112: 'ReCardio è totalmente sicuro',
lt113: 'Non ha effetti collaterali',
lt114: 'Risolve il problema principale dell’ipertensione',
lt115: 'E’ compatibile con persone di qualsiasi età',
lt116: 'ha già aiutato migliaia di persone a tornare in salute !',
lt117: 'Marcella Cavani, Trento<br>61 anni',
lt118: '4 anni fa mi è stata fatta la tremenda diagnosi, ipertensione arteriosa maligna con danneggiamento dei vasi sanguigni. La mia vita si è tramutata in un inferno. I dottori "mi curavano" con pillole che mi facevano stare solo peggio. Fortunatamente mia figlia ha scoperto ReCardio in tempo. Mi sono bastate due settimane di ciclo per liberarmi completamente dei sintomi. La pressione ha smesso di "balzare" già dopo poche assunzioni ed è tutt’ora stabile nella norma.  Mi sento nuovamente una persona in salute!',
lt119: 'Alessandro Proietti, Milano<br>58 anni',
lt120: 'L’ipertensione mi è comparsa a 53 anni ed è andata sempre peggiorando. Avevo sempre più paura e sopportavo una crisi dopo l’altra, la pressione arrivava a livelli incredibili. Non riuscivo ad abbassarla in nessun modo. Fortunatamente ho incontrato un bravo cardiologo. Mi ha prescritto l’assunzione di XX per due settimane. All’inizio non ci credevo affatto che mi avrebbe aiutato. Ma già dopo tre giorni di assunzione mi sono sentito nettamente meglio ',
lt121: 'la pressione si è stabilizzata',
lt122: 'sono passati i mal di testa e le fitte al cuore. Ora vivo senza aver paura della mia vita, senza aspettarmi l’infarto o un ictus da un momento all’altro!',
lt123: 'Vanessa Battaglia, Catania<br>52 anni',
lt124: 'Da quando ho 30 anni ho problemi di peso,poi è comparso anche il diabete, e come conseguenza l’ipertensione. E’ tutto ereditario, quindi mi sono messa l’anima in pace. Non vivevo, sopravvivevo. Prendevo pillole in continuazione, ero ormai dipendente. Dopo aver ascoltato il consiglio di un’amica ho fatto un ciclo con ReCardio. Da allora ho iniziato a vivere una nuova vita! I problemi di pressione sono scomparsi, ora sono una persona totalmente in salute. A chiunque abbia avuto questo tipo di problemi raccomando questo preparato e vi auguro una pronta guarigione!',
lt125: 'Come ordinare',
lt126: 'Primo passo',
lt127: 'Compilate il modulo d’ordine più in basso',
lt128: 'Secondo passo',
lt129: 'Attendete la chiamata dell’operatore',
lt130: 'Terzo passo',
lt131: 'Pagate solo al momento della ricezione del pacco alla posta o dal corriere',
lt132: 'EVITATE I FALSI!',
lt133: 'Per evitare falsi e analoghi di bassa qualità effettuate l’acquisto solo sul sito in questione .',
lt134: '100% GARANZIA DI QUALITA’!',
lt135: 'NON LASCIATE DA PARTE LA BATTAGLIA CONTRO L’IPERTENSIONE FINCHE’ SIETE IN TEMPO!',
lt136: 'SCONFIGGETE IL MALESSERE GIA’ OGGI!',
lt137: 'Il prezzo è più basso grazie all’azione dell’ ASSOCIAZIONE DEI CARDIOLOGI ITALIANI ',
lt138: 'Garantiamo che i vostri dati personali saranno al sicuro!',
lt139: 'Rimangono solo:',
lt140: 'confezioni',

}; 

function Translater () {
            for (class_name in new_lang) {
                var elements = document.getElementsByClassName(class_name);
                if (elements.length) {
                    for (key in elements) {
                        elements[key].innerHTML = new_lang[class_name];
                    }
                }
            }
};